### ISSUE TITLE
Problem typing mutual definitions

### ISSUE THREAD

**Issue by mbenke** [rodrigogribeiro/solcore#2]
There seems to be a problem when typing mutually recursive definition (even without recursion, if use precedes declaration)

Example:

```
cabal run sol-core.cabal -- -f mutual.solc          
Results: Word

Results: forall a . a

contract Mutual {
   function main () {
      return f()
   }
   function f () {
      return 42
   }
}
```

`main` seems to be typed as `forall a. a`

**Comment by rodrigogribeiro** [comment]
Fixed on defunctionalization branch.
